
clear t
syms t 

rad = pi/180;
theta = 0*rad;
Lx = 1;
Ly = 1;
v=350000;
c=3e8;


eq = ...
sqrt( ...
    (...
        (1-v*cos(theta))^(-1)*(Lx + v*cos(theta)*t) ...
    )^2 + ( ...
        (1-v*sin(theta))^(-1)*(Ly + v*sin(theta)*t) ...  
    )^2 ...    
) / ...
sqrt( ...
    ( ...
        (c-v*cos(theta)*t)^(2) + (c-v*sin(theta)*t)^(2)...
    ) ...
) - t;

solve(eq)