function [fitresult, gof] = fitp(pu)
%CREATEFIT(PU)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      Y Output: pu
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 22-Nov-2014 16:05:21


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( [], pu );

% Set up fittype and options.
ft = fittype( 'poly9' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData,'o');
legend( h, 'pu', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
ylabel( 'pu' );
grid on


