function [tt,azimuth,temp,magneticscalar,magneticx,magneticy,magneticz,accelerationscalar,accelerationx,accelerationy,accelerationz,lifecount] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [DATE1,TIME,AZIMUTH1,PITCH,ROLL,TEMPERATURE,DEPTH,MAGSCALAR,MAGX,MAGY,MAGZ,ACCSCALAR,ACCX,ACCY,ACCZ,GYROSCALAR,GYROX,GYROY,LIFECOUNT]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [DATE1,TIME,AZIMUTH1,PITCH,ROLL,TEMPERATURE,DEPTH,MAGSCALAR,MAGX,MAGY,MAGZ,ACCSCALAR,ACCX,ACCY,ACCZ,GYROSCALAR,GYROX,GYROY,LIFECOUNT]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Date1,Time,Azimuth1,Pitch,Roll,Temperature,Depth,MagScalar,MagX,MagY,MagZ,AccScalar,AccX,AccY,AccZ,GyroScalar,GyroX,GyroY,LifeCount]
%   = importfile('x01.txt',2, 25530);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/11/10 23:21:54

%% Initialize variables.
delimiter = ';';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]);
rawCellColumns = raw(:, [1,2]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
date = rawCellColumns(:, 1);
time = rawCellColumns(:, 2);
azimuth = cell2mat(rawNumericColumns(:, 1));
pitch = cell2mat(rawNumericColumns(:, 2));
roll = cell2mat(rawNumericColumns(:, 3));
temp = cell2mat(rawNumericColumns(:, 4));
depth = cell2mat(rawNumericColumns(:, 5));
magneticscalar = cell2mat(rawNumericColumns(:, 6));
magneticx = cell2mat(rawNumericColumns(:, 7));
magneticy = cell2mat(rawNumericColumns(:, 8));
magneticz = cell2mat(rawNumericColumns(:, 9));
accelerationscalar = cell2mat(rawNumericColumns(:, 10));
accelerationx = cell2mat(rawNumericColumns(:, 11));
accelerationy = cell2mat(rawNumericColumns(:, 12));
accelerationz = cell2mat(rawNumericColumns(:, 13));
gyroScalar = cell2mat(rawNumericColumns(:, 14));
gyroX = cell2mat(rawNumericColumns(:, 15));
gyroY = cell2mat(rawNumericColumns(:, 16));
lifecount = cell2mat(rawNumericColumns(:, 17));
tt = rem(datenum(datestr(time(:))),1) + datenum(datestr(date(:)));

