function [pressure,temp,hum,tt] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [PRESSURE,TEMP,HUM,TT] = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   [PRESSURE,TEMP,HUM,TT] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads
%   data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [pressure,temp,hum,tt] = importfile('tphmatlab.txt',1, 6233);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/10/08 09:24:08

%% Initialize variables.
delimiter = '\t';
if nargin<=3
    startRow = 1;
    endRow = inf;
end
if ~exist('filename')
    filename = 'C:\Users\an\Desktop\tphmatlab.txt';
end

%% Format string for each line of text:
%   column3: double (%f)
%	column5: double (%f)
%   column6: double (%f)
%	column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%f%*s%f%f%*s%*s%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
pressure = dataArray{:, 1};
temp = dataArray{:, 2};
hum = dataArray{:, 3};
tt = dataArray{:, 4};

